const connection = require("../config/connection");
const { User, Thought } = require("../models");

connection.on("error", (err) => err);

connection.once("open", async () => {
    console.log("connected");

    // Drop existing users
    await User.deleteMany({});

    // Drop existing thoughts
    await Thought.deleteMany({});

    // Array of objects to hold the users
    const user = [
        {
            username: "testuser",
            email: "testuser@gmail.com",
        },
        {
            username: "testuser3",
            email: "testuser3@gmail.com",
        },
        {
            username: "testuser2",
            email: "testuser2@gmail.com",
        },
        {
            username: "testuser1",
            email: "testuser1@gmail.com",
        },
    ];

    // Array of objects to hold the thoughts
    const thought = [
        {
            thought: "i think the sky is not blue... its our eyes problem !?",
            username: "testuser",
        },
        {
            thought: "Can i fly while im sleeping ?",
            username: "testuser3",
        },
        {
            thought: "lets do better ?",
            username: "testuser2",
        },
        {
            thought: "this is wierd they are telling all of our thoughts are generated by programmers ! we know thats a lie i have feelings",
            username: "testuser1",
        },
    ];

    // Add users to the collection and await the results
    await User.collection.insertMany(user);

    // Add thoughts to the collection and await the results
    await Thought.collection.insertMany(thought);

    // Log out the seed data to indicate what should appear in the database
    console.table(user);
    console.table(thought);
    console.info("Seeding complete!");
    process.exit(0);
});